title: Minimal theme
logo: <img src="https://user-images.githubusercontent.com/13935213/117522473-00e09d00-af8a-11eb-80de-a0a0937c9d38.png" width="250" height="250">
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
